package org.nexus.d2h.notification;

public enum NotificationEventType {
    FINANCE_TRANSACTION_CREATED,
    FINANCE_TRANSACTION_REVERSED,
    FINANCE_TRANSACTION_ADJUSTED,
    FINANCE_UPLOAD_COMPLETED,
    RECHARGE_CREATED,
    RECHARGE_REVERSED,
    RECHARGE_UPLOAD_COMPLETED,
    SUBSCRIPTION_EXPIRY_WARNING
}
